name: build_push_slim_container

on:
  release:
    types:
      - created

jobs:
  docker-slim-build-container:
    runs-on: ubuntu
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      -
        name: Tests
        run: |
          go mod tidy
          go test -v ./pkg/handlers
      -
        name: Login to github registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      -
        name: Get Tag Name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Build the Docker image
        run: |
          go build ./cmd/main.go
          sudo curl https://downloads.dockerslim.com/releases/1.39.1/dist_linux.tar.gz -o ./dist_linux.tar.gz && sudo tar xf ./dist_linux.tar.gz -C . && sudo mv dist_linux/* /usr/bin && sudo chmod +x /usr/bin/docker-slim && sudo chmod +x /usr/bin/docker-slim-sensor
          docker-slim build --tag martijnvdp/eks-test-app:$VERSION --tag martijnvdp/eks-test-app:latest --include-cert-all --http-probe=false --continue-after 60 --dockerfile ./Dockerfile --dockerfile-context . --delete-generated-fat-image
          docker push ghcr.io/martijnvdp/eks-test-app --all-tags
