name: build_push_slim_container

on:
  release:
    types:
      - created

jobs:
  docker-slim-build-container:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      -
        name: Tests
        run: |
          go mod tidy
          go test -v ./pkg/handlers
      # - 
      #   name: Login to GitHub Container registry
      #   uses: docker/login-action@v1
      #   env:
      #     GITHUB_USER: ${{ github.actor }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     registry: ghcr.io
      #     username: $GITHUB_USER
      #     password: ${{ secrets.GH_TOKEN }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github
      - run: aws sts get-caller-identity
      -
        name: Get Tag Name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Build the Docker image
        run: |
          sudo curl https://downloads.dockerslim.com/releases/1.40.0/dist_linux.tar.gz -o ./dist_linux.tar.gz && sudo tar xf ./dist_linux.tar.gz -C . && sudo mv dist_linux/* /usr/bin && sudo chmod +x /usr/bin/docker-slim
          rm ./dist_linux.tar.gz
          docker-slim build --tag {{ secrets.AWS_ECR_TARGET }}:$VERSION --tag {{ secrets.AWS_ECR_TARGET }}:latest --include-cert-all --http-probe=false --continue-after 60 --dockerfile ./Dockerfile --dockerfile-context . --delete-generated-fat-image
          docker push {{ secrets.AWS_ECR_TARGET }} --all-tags

        shell: bash
        env:
          VERSION: ${{ steps.tag_name.outputs.SOURCE_TAG }}

